### ISSUE TITLE
wand not doing ANYTHINg

### ISSUE THREAD

**Issue by Chris-FireFox** [FusionLord/EMCBuildersWand#1]
well on the latest version of builders paradise and this wand seems to do nothing as there is no way of setting what block you want it to place

**Comment by FusionLord** [comment]
You have to have the knowledge of the block, just like anything else, you can toggle that function in the config.

**Comment by Chris-FireFox** [comment]
the block IS known in my transmutation tablet however as i said. there dont seem to be a way for telling the wand WHAT block to use as i have tried several known blocks and none seems to be able to be set in the wand

**Comment by FusionLord** [comment]
I feel you are missing the point here. It is a builders wand, you use it just like anyother builders wand. The only difference is you dont have blocks in your inventory. Take dirt for example, make sure you have emc in your network, make sure you have knowledge of dirt, then right click the wand on dirt in world. I didnt change the functionality of the wand just the resource type.

**Comment by Chris-FireFox** [comment]
and yet it will not place any blocks known in the world like a normal builders wand would do and yues i DO know the blocks im trying to place

**Comment by FusionLord** [comment]
There is no setting of the block you want to place. It works as i described it in the previous reply, i will do some testing when i get home from work in say 12 hours.

**Comment by FusionLord** [comment]
Fixed in build 1.8
